GibJohn/Controllers/HomeController.cs
using GibJohn.Data;
using GibJohn.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;
using System.Diagnostics;

namespace GibJohn.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult ShowSearchForm()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> ShowSearchResult(String SearchPhrase)
        {
            var userDetails = await _context.Users
                .Where(u => u.Id == SearchPhrase)
                .Select(u => new {FirstName = u.FirstName, LastName = u.LastName, SessionsCompleted = u.SessionsCompleted, StudentID = SearchPhrase})
                .FirstOrDefaultAsync();
            if (userDetails != null)
            {
                ViewBag.UserDetails = userDetails;
                return View();
            }
            else
            {
                return NotFound();
            }
        }
    }
}

GibJohn/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GibJohn.Data;
using GibJohn.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Security.Claims;

namespace GibJohn.Controllers
{
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NotesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Notes
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var courseIds = await _context.Registration
                .Where(r => r.UserId == userId)
                .Select(r => r.CourseId)
                .ToListAsync();

            var courses = await _context.Note
                .Where(c => courseIds.Contains(c.CourseId))
                .ToListAsync();

            Console.WriteLine(courses.Count);
            Console.WriteLine(courses);

            return _context.Course != null ?
                View(courses) :
                Problem("Yeah");
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Note == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .FirstOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }
            await IncrementCounter();
            return View(note);
        }

        // GET: Notes/Create
            public IActionResult Create()
            {
                var courses = _context.Course.ToList(); // Assuming you have a DbContext named 'db'
                ViewBag.Courses = courses.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }).ToList();


            return View();
            }

        // POST: Notes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CourseId,Topic,Notes,Video")] Note note)
        {
            note.Course = _context.Course.Where(c => c.Id == note.CourseId).ToList()[0];
            ModelState.Clear();
            TryValidateModel(note, nameof(Note));
            if (ModelState.IsValid)
            {
                _context.Add(note);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            var courses = _context.Course.ToList(); // Assuming you have a DbContext named 'db'
            ViewBag.Courses = courses.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }).ToList();
            return View(note);
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Note == null)
            {
                return NotFound();
            }

            var note = await _context.Note.FindAsync(id);
            if (note == null)
            {
                return NotFound();
            }
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CourseId,Topic,Notes,Video")] Note note)
        {
            if (id != note.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(note);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoteExists(note.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Note == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .FirstOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Note == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Note'  is null.");
            }
            var note = await _context.Note.FindAsync(id);
            if (note != null)
            {
                _context.Note.Remove(note);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private async Task IncrementCounter()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _context.Users.FindAsync(userId);
            if (user == null)
            {
                user.SessionsCompleted++;
                _context.SaveChangesAsync();
            }
        }

        private bool NoteExists(int id)
        {
          return (_context.Note?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GibJohn/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GibJohn.Data;
using GibJohn.Models;

namespace GibJohn.Controllers
{
    public class RequestsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RequestsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Requests
        public async Task<IActionResult> Index()
        {
            return _context.Request != null ?
                        View(await _context.Request.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Request'  is null.");
        }

        // GET: Requests/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,CourseLevel,ExamBoard,Comment")] Request request)
        {
            if (ModelState.IsValid)
            {
                _context.Add(request);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(request);
        }
    }
}

GibJohn/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <p class="display-4">Welcome</p>
    <div class="d-flex flex-row justify-content-around align-content-center align-items-center container-fluid dashboard-actions" style="height: 65vh;">
    @{
        if (!User.Identity.IsAuthenticated)
        {
            // Message displayed if user isnt signed in
            <p class="display-4 text-center">Please log in to access the dashboard.</p>
        }
        
        else if (User.IsInRole("Management"))
        {
            <!---ADMIN DASHBOARD--->
                <!--Add courses option-->
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Add Courses</h5>
                        <p class="card-text">Allows for courses to be added for students to view and join.</p>
                        <a asp-controller="Courses" asp-action="Create" class="btn btn-primary">Go</a>
                    </div>
                </div>
                <!--Add quizzes option-->
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Add Quizzes</h5>
                        <p class="card-text">Allows for quizzes to be added for students to view and attempt.</p>
                        <a onclick="alert('This feature has not been implemented yet. ');" class="btn btn-primary">Go</a>
                    </div>
                </div>
                <!--Add notes option-->
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Add Notes</h5>
                        <p class="card-text">Allows for notes to be added for enrolled students to view.</p>
                        <a asp-controller="Notes" asp-action="Create" class="btn btn-primary">Go</a>
                    </div>
                </div>
                <!--View requested courses option-->
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">View Course Requests</h5>
                        <p class="card-text">Shows the courses that teachers have requested to be added.</p>
                        <a asp-controller="Requests" asp-action="Index" class="btn btn-primary">Go</a>
                    </div>
                </div>
        }
        
        else if (User.IsInRole("Teacher"))
        {
            <!--TEACHER DASHBOARD-->
                <!--Find student option-->
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Find Student</h5>
                        <p class="card-text">Allows students to be searched by their user ID and shows the amount of notes viewed.</p>
                        <a asp-controller="Home" asp-action="ShowSearchForm" class="btn btn-primary">Go</a>
                    </div>
                </div>
                <!--Dashboard option-->
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Dashboard</h5>
                        <p class="card-text">A page which shows all tracked students' metrics on graphs and tables.</p>
                        <a onclick="alert('This feature has not been implemented yet. ');" class="btn btn-primary">Go</a>
                    </div>
                </div>
                <!--Request course option-->
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Request Course</h5>
                        <p class="card-text">Is this website missing a course which you teach or need? Submit it here.</p>
                        <a asp-controller="Requests" asp-action="Create" class="btn btn-primary">Go</a>
                    </div>
                </div>
             
        }
        
        else if (User.IsInRole("Student"))
        {
        <!--STUDENT DASHBOARD-->
                <!--Find courses option-->
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Find Courses</h5>
                        <p class="card-text">View our available courses and join courses which you are in.</p>
                        <a asp-controller="Courses" asp-action="Index" class="btn btn-primary">Go</a>
                    </div>
                </div>
                <!--My courses option-->
                <div class="card" style="width: 18rem;">
                     <div class="card-body">
                        <h5 class="card-title">My Courses</h5>
                        <p class="card-text">View the courses that you have already joined.</p>
                        <a asp-controller="Courses" asp-action="MyCourses" class="btn btn-primary">Go</a>
                    </div>
                </div>
                <!--Notes option-->
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Notes</h5>
                        <p class="card-text">View notes related to the courses which you have joined.</p>
                        <a asp-controller="Notes" asp-action="Index" class="btn btn-primary">Go</a>
                    </div>
                </div>
                <!--Quizzes option-->
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Quizzes</h5>
                        <p class="card-text">Take quizzes and tests related to the courses which you have joined.</p>
                        <a onclick="alert('This feature has not been implemented yet. ');" class="btn btn-primary">Go</a>
                    </div>
                </div>
        }

    }
    </div>
</div>

GibJohn/Views/Home/ShowSearchForm.cshtml
@{
    ViewData["Title"] = "ShowSearchForm";
}

<h1>Search student by ID</h1>
<div class="row">
    <div class="col-md-4">
        <!--Sends data from the form to the code in the controller-->
        <form asp-action="ShowSearchResult">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="SearchPhrase" class="control-label">Enter User ID</label>
                <input name="SearchPhrase" class="form-control bg-dark text-white" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GibJohn/Views/Home/ShowSearchResult.cshtml
@{
    ViewData["Title"] = "ShowSearchResult";
    var student = ViewBag.UserDetails;
}

<!--Display student details which have been retrieved from the controller-->
<div class="text-center">
    <h2>Showing results for student ID @student.StudentID</h2>
    <h4>Name: @student.FirstName @student.LastName</h4>
    <h4>Notes Viewed: @student.SessionsCompleted</h4>
</div>